### ISSUE TITLE
程序启动就报错

### ISSUE THREAD

**Issue by RavenCage** [AiKirito/Clash_For_Windows_Ultra#4]
![快照1](https://github.com/AiKirito/Clash_For_Windows_Ultra/assets/126802578/8524dcf7-592b-464d-adab-1cf14b2aa843)
不论是3.1或者3.1 fixed版本都是这个错误。我手动替换1.18.0-go版本也是如此。望修复。

**Comment by RavenCage** [comment]
哈哈，捣鼓两下，自己弄好了。

**Comment by linxiazhixi** [comment]
> 哈哈，捣鼓两下，自己弄好了。

请问怎么弄好的？我现在3.2一直报错

**Comment by RavenCage** [comment]
你要自己换内核，比如amd64或者compatible版，或者compatible-go120版，我用最后那个go120版就好了。

**Comment by linxiazhixi** [comment]
> 你要自己换内核，比如amd64或者compatible版，或者compatible-go120版，我用最后那个go120版就好了。

谢谢，我就说怎么换内核都报错，原来要GO120啊，OK了

**Comment by Skyline5723** [comment]
> 你要自己换内核，比如amd64或者compatible版，或者compatible-go120版，我用最后那个go120版就好了。

都试了都不行怎么破

**Comment by RavenCage** [comment]
> > 你要自己换内核，比如amd64或者compatible版，或者compatible-go120版，我用最后那个go120版就好了。
> 
> 都试了都不行怎么破
![快照1](https://github.com/AiKirito/Clash_For_Windows_Ultra/assets/126802578/14705479-7c5b-49da-853d-68db3d964d64)


那就最后一招，不停改这两个动态端口的选项，我开始就是这么不停改来改去，喵的，最后就行了。

**Comment by Skyline5723** [comment]
> > > 你要自己换内核，比如amd64或者compatible版，或者compatible-go120版，我用最后那个go120版就好了。
> > 
> > 
> > 都试了都不行怎么破
> > ![快照1](https://private-user-images.githubusercontent.com/126802578/296979060-14705479-7c5b-49da-853d-68db3d964d64.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjY2ODYsIm5iZiI6MTcwNTQ2NjM4NiwicGF0aCI6Ii8xMjY4MDI1NzgvMjk2OTc5MDYwLTE0NzA1NDc5LTdjNWItNDlkYS04NTNkLTY4ZGIzZDk2NGQ2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwNDM5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDgyYmQ5MjJlMWFjZWU0MTQ3ZDEwZDEwMjY0NDQ4MjhlNTMzMzJiZWNiY2ZjOWUyYjE1YTZjNjUzZjViM2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4ebTxfpgrfxuOYNmQ1H1vxi6ESXmhgiAEgtLCuBSWn0)
> 
> 那就最后一招，不停改这两个动态端口的选项，我开始就是这么不停改来改去，喵的，最后就行了。

草，昨天换内核换了一天都不行，今天打开就可以了，妈的
